version: '3.8'
services:
  ed-training-audio:
    image: ghcr.io/um-xr2learn-enablers/ed-training-audio:latest-gpu
    build:
      context: 'Supervised_Training/Supervised_Audio_Modality'
      dockerfile: 'Dockerfile-gpu'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  ssl-audio:
    image: ghcr.io/um-xr2learn-enablers/ssl-audio:latest-gpu
    build:
      context: 'SSL_Training/SSL_Audio_Modality'
      dockerfile: 'Dockerfile-gpu'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]


  ssl-features-generation-audio:
    image: ghcr.io/um-xr2learn-enablers/ssl-features-generation-audio:latest-gpu
    build:
      context: 'SSL_Features_Extraction/SSL_Features_Extraction_Audio_Modality'
      dockerfile: 'Dockerfile-gpu'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
  
  ed-training-bm:
    image: ghcr.io/um-xr2learn-enablers/ed-training-bm:latest-gpu
    build:
      context: 'Supervised_Training/Supervised_BM_Modality'
      dockerfile: 'Dockerfile-gpu'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
  
  ed-training-body-tracking:
    image: ghcr.io/um-xr2learn-enablers/ed-training-body-tracking:latest-gpu
    build:
      context: 'Supervised_Training/Supervised_Body_Tracking_Modality'
      dockerfile: 'Dockerfile-gpu'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  ssl-bm:
    image: ghcr.io/um-xr2learn-enablers/ssl-bm:latest-gpu
    build:
      context: 'SSL_Training/SSL_BM_Modality'
      dockerfile: 'Dockerfile-gpu'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  ssl-features-generation-bm:
    image: ghcr.io/um-xr2learn-enablers/ssl-features-generation-bm:latest-gpu
    build:
      context: 'SSL_Features_Extraction/SSL_Features_Extraction_BM_Modality'
      dockerfile: 'Dockerfile-gpu'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
