from setuptools import setup

setup(
    name='pre_processing_body_tracking_modality',
    version='0.5.0',
    description='Pre processing component for the Body Tracking modality using data generated by Magic XRoom.',
    author='UM-XR2Learn-Enablers',
    packages=['pre_processing_body_tracking_modality'],
    zip_safe=False
)
